# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-03 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_churchevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchevent',
            name='address',
            field=models.CharField(default='church', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='churchevent',
            name='description',
            field=models.CharField(default='test Desc', max_length=1000),
            preserve_default=False,
        ),
    ]
