# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-10 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171208_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('document', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='Sermons',
        ),
    ]
