# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-10 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171210_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='document',
            field=models.FileField(upload_to='static/uploads/'),
        ),
    ]
